### ISSUE TITLE
공통 개발 환경 세팅

### ISSUE THREAD

**Issue by Ujaa** [boostcampwm-2024/web31-BooLock#1]
## Task
- [x] pnpm, node.js 버전 확인
- [x] 모노레포 구성
- [x] vite로 react 설치
- [x] [be]express 설치
- [x] [global] typescript
- [x] [fe] 폴더 구조 fsd 아키텍처 적용
- [x] [be] 폴더 구조 mvc 패턴 적용
- [x] [fe] Tailwind-CSS
- [x] [fe] zustand + Tanstack-Query
- [x] [be] mongoose
- [x] [fe] blockly
- [x] [fe] storybook
- [x] [fe] react-router
- [x] [fe] axios
- [x] 필요한 script 만들어두기
