### ISSUE TITLE
[hotfix] tsconfig-paths 설치 누락 및 swagger-output.json 연동 안되는 문제 발생

### ISSUE THREAD

**Issue by lee0jae330** [boostcampwm-2024/web31-BooLock#101]
## 🐞 Bug
- [ ] tsconfig-paths 설치 누락
![{977D9449-2582-4771-A576-422AC3973E4E}](https://github.com/user-attachments/assets/51fea974-e411-46de-b7b9-e11e9507b191)
- [ ] swagger-autogen을 하지 않고 `pnpm dev`를 바로 실행할 때 빌드가 안되는 오류 발생

## 📝 Todo
- [ ] server 디렉토리 tsconfig-paths 모듈 설치
- [ ] package.json 스크립트 수정
