### ISSUE TITLE
[refactor] 멘토님 코드 리뷰 반영

### ISSUE THREAD

**Issue by lee0jae330** [boostcampwm-2024/web31-BooLock#117]
## 멘토님 코드 리뷰 반영
- [ ] 클라이언트 api 요청 코드 개선
- [ ] tanstack query의 쿼리 키를 관리하는 소스 파일 추가

## 📝 Todo
- [ ] api 요청 로직 수정
- [ ] queryKey.ts 추가
