### ISSUE TITLE
[추가작업] 코드 하이라이팅 라이브러리 구현

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#150]
## TASK
- 코드 색상 하이라이팅
- 워크스페이스에 블록 잡으면 해당 코드에 포커싱 
- 미리보기 코드는 수정 불가

## 📝 Todo
- [ ] 코드 하이라이팅 라이브러리 구현
- [ ] 워크스페이스에 블록 잡으면 해당 코드에 포커싱 
- [ ] 미리보기 코드는 수정 불가
