### ISSUE TITLE
[1-8] 사용자는 목록에서 각 워크스페이스에서 만들고 있는 프리뷰 화면을 볼 수 있다.

### ISSUE THREAD

**Issue by Honghyeonji** [boostcampwm-2024/web31-BooLock#175]
## [1-8] 사용자는 목록에서 각 워크스페이스에서 만들고 있는 프리뷰 화면을 볼 수 있다.
- 워크스페이스 목록 아이템에서 프리뷰 화면을 썸네일로 확인할 수 있다.

## 📝 Todo
- [ ] 워크스페이스 저장 시 프리뷰창 캡쳐
- [ ] 워크스페이스 저장 시 스토리지로 썸네일 저장 및 경로 저장
- [ ] 워크스페이스 목록 조회 시 썸네일 경로 반환 및 이미지 렌더링 최적화 작업
