### ISSUE TITLE
 [bug] html generator 적용 에러 + 미리보기 화면 크기 수정

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#176]
## [3-8] 사용자는 HTML/CSS 코드를 코드 블록으로 확인할 수 있다.

- html generator 할 때 잘 안먹힘 - class 블록에 특정 오류 발생 추정
- html 태그에 css 적용 안됨 & html 코드에 클래스 안들어감
- preview창 작게보임
- 블록이 body를 벗어나도 프리뷰에 계속 보임

## 📝 Todo

- [ ] html generator 할 때 잘 안먹힘 - class 블록에 특정 오류 발생 추정
- [ ] html 태그에 css 적용 안됨 & html 코드에 클래스 안들어감
- [ ] preview창 작게보임
- [ ] 블록이 body를 벗어나도 프리뷰에 계속 보임
