### ISSUE TITLE
[추가 작업] 사용자 가이드

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#183]
## 📝 Todo
- [x] 시안 & 문구 정하기 (코치마크로 픽스)
- [ ] 단계별 컴포넌트 하이라이팅
- [x] 디자인 시안대로 구현
- [ ] 코치마크 꼬리
- [x] localStorage로 워크스페이스 처음 입장시 적용하기
