### ISSUE TITLE
[추가 작업] 워크스페이스 샘플 만들기

### ISSUE THREAD

**Issue by Ujaa** [boostcampwm-2024/web31-BooLock#185]
## Tasks
- [x] 워크스페이스 샘플 생성 버튼을 추가한다.
- [x] 샘플을 DB에 미리 저장해둔다.
- [x] 샘플 생성 버튼을 누르면 저장해둔 샘플이 생성되도록 한다.
- [x] 유저가 처음 만들어지면 샘플을 하나 추가해둔다.
