### ISSUE TITLE
[bug] select 관련 버그

### ISSUE THREAD

**Issue by Ujaa** [boostcampwm-2024/web31-BooLock#186]
### 1차
select option이 너무 많으면 길어지는 현상

![Image](https://github.com/user-attachments/assets/e2132ccd-5965-4cda-b665-83481e4a2cd3)

스크롤할 때 위치가 고정되는 현상

https://github.com/user-attachments/assets/e87f4d5e-b9ba-4c3f-ab32-11a5da6b3280

새로고침 이후에 default 값이 들어가지 않는 현상

![Image](https://github.com/user-attachments/assets/ece0e8a4-84dd-4c7f-ad30-625ca932b64b)

## 📝 Todo
- [x] 클래스가 많아져도 화면을 넘치지 않도록 options의 위치를 조정한다.
- [x] 너무 길어지면 스크롤되도록 한다.
- [x] 스크롤을 하면 select가 따라서 움직이거나 꺼지도록 한다.
- [x] 새로고침 이후에도 option에 선택된 값이 있으면 기본 값을 넣어주도록 한다.
