### ISSUE TITLE
[2-9] 사용자는 채점 결과에 따른 팝업창을 볼 수 있다.

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#19]
## TASK

- [ ] 정답을 맞췄다면 다음 단계로 이동하라는 모달창을 띄운다. 
- [ ] “다음 단계” 버튼을 누르면 상단의 단계를 하나 진행시키고 해당 단계의 [학습 결과]를 보여준다.
- [ ] 정답을 틀렸다면 “틀렸습니다.” 라는 모달창을 띄운다.
- [ ] “정답을 틀렸습니다” 모달창에서 “다시 시도하기” 버튼을 누르면 모달창을 닫는다.
