### ISSUE TITLE
[chore] 홈페이지 초기 로딩 시 스켈레톤 UI 적용 및 code-highlighter 스토리북 추가

### ISSUE THREAD

**Issue by lee0jae330** [boostcampwm-2024/web31-BooLock#238]
## 태스크
- [ ] 홈페이지 초기 로딩 시 스켈레톤 UI를 렌더링한다.
- [ ] code-highlighter 컴포넌트에 스토리북을 추가한다.

## 📝 Todo
- [ ] 로딩 컴포넌트 추가
- [ ] code-highlighter 컴포넌트에 스토리북 추가
