### ISSUE TITLE
[3-3] 사용자는 “HTML” 탭을 누르면 현재 블록의 html 코드를 볼 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#24]
## TASK

- [ ] HTML 태그 블록에 따른 html 코드를 파싱한다.
- [x] 입력한 클래스명이 해당 html 코드에 반영된다.
       `<p class="클래스명1"> </p>`
- [ ] 파싱된 HTML 코드를 프리뷰에서 보여준다.
