### ISSUE TITLE
[4-4] 워크스페이스 블록 삭제, 스케일 조정 기능 설정 및 커스텀

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#26]
## TASK

- [x] 블록을 휴지통 위에 올려두면, 휴지통 이미지가 바뀐다.
- [x] 휴지통 이미지를 커스텀한다.
- [x] zoom관련 아이콘들을 커스텀한다.
- [x] zoom관련 아이콘 및 휴지통 위치를 각각 우측 상단 및 우측 하단에 위치시킨다.
