### ISSUE TITLE
[1-1] 사용자는 [추가]하기 버튼을 눌러서 새로운 워크스페이스를 추가할 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#3]
## TASK
- [ ] [+] 추가 버튼을 누르면 생성 중 로딩 화면을 보여준다.
- [ ] [+] 버튼은 한 번 누르면 서버에서 응답이 오기 전까지 비활성화된다.
- [ ] 서버 측에서 새로운 워크 스페이스 룸넘버 ID를 생성 후 DB에 저장한다.
- [ ] 새로운 룸넘버 저장에 실패하면 [워크 스페이스 생성 실패] 토스트 메시지를 클라이언트 측에서 보여준다.
- [ ] 서버에서 성공적으로 생성한 룸넘버가 응답으로 넘어오면 해당 룸넘버를 로컬스토리지에 저장한다.
- [ ] 새로운 워크스페이스를 생성하면 해당 워크 스페이스로 이동한다.
