### ISSUE TITLE
[5-1] 사용자는 스타일 블록을 새롭게 만들 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#36]
## TASK

- [ ] input 박스에 추가할 스타일(클래스)명을 입력한다.
- [ ] [+]버튼을 누르면 서버에 해당 스타일명 생성 요청을 한다.
- [ ] 생성 완료시 클라이언트 측에선 새로운 스타일블록을 보여준다.
- [ ] 생성 실패시 클라이언트 측에선 [스타일 블록 생성 실패] 토스트메시지를 보여준다.
