### ISSUE TITLE
[5-2] 사용자는 사용할 스타일 정보를 입력하고 체크해서 사용할 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#37]
## TASK

- [ ] 기본으로 적용되어 있는 스타일은 체크를 해제할 수 없다.
- [ ] 스타일의 값은 숫자, option, 색상 코드 중 알맞는 타입을 사용한다.
- [ ] 스타일에 따라 여러 타입을 조합해 값을 입력받는다.
- [ ] 숫자는 px 단위 값으로 취급한다.
- [ ] 체크 박스에 체크하지 않아도 값을 입력하면 자동으로 체크 박스가 체크된다.
