### ISSUE TITLE
[6-2] 사용자는 워크스페이스 이름을 더블클릭하면 이름을 변경할 수 있다.

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#39]
## TASK

- [ ] 이름을 변경한 뒤 enter키 혹은 input창의 focus가 풀리면 서버로 PUT api 요청을 보낸다.
- [ ] 서버에서는 변경할 워크스페이스 이름으로 DB를 변경한다.
- [ ] 변경 실패하면 [워크스페이스 이름 변경 실패] 토스트 메세지를 클라이언트 측에서 보여준 뒤, 기존의 이름으로 다시 바꾼다
- [ ] 변경 성공시에는 따로 토스트 메세지를 보여주지 않는다.

## 비고

워크스페이스 이름의 제한은 20자 이내로 한다.
