### ISSUE TITLE
[6-3] 사용자는 [저장] 버튼을 통해 현재 워크 스페이스의 상태를 DB에 저장할 수 있다.

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#41]
## TASK

- [ ] [저장]버튼을 누르면 저장중 로딩 화면을 띄우고 웹페이지 전체 클릭을 비활성화한다.
- [ ] 워크스페이스의 캔버스 상태를 xml로 변환하고 텍스트화 시킨다.
- [ ] 워크스페이스의 css 상태를 코드로 파싱하고 텍스트화 시킨다.
- [ ] 미리보기 창을 캡처한 것을 thumbnail로 저장한다.
- [ ] 캔버스 및 css 상태를 DB에 저장한다.
- [ ] 저장 성공 시 클라이언트측에서 [저장 성공] 토스트메시지를 띄운다.
- [ ] 저장 실패 시 클라이언트측에서 [저장 실패] 토스트메시지를 띄운다.
