### ISSUE TITLE
[5-7] 사용자는 스타일 삭제 버튼을 통해 스타일을 삭제할 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#46]
## TASK

- ~~모달창의 취소버튼 클릭시 모달창을 없앤다.~~
- ~~삭제 버튼 클릭시 재확인 모달창 생성~~
- ~~확인 버튼 클릭시 해당 스타일 블록을 DB에서 삭제한다.~~
- [x] flyout 내 블록에서 오른쪽 버튼 클릭시 삭제하기 버튼이 뜬다.
- [x] 삭제에 성공하면 스타일 블록 리스트에서 해당 스타일 블록을 삭제한 후 [스타일 블록 삭제 완료] 토스트 메시지를 클라이언트 측에서 보여준다.
- [x] 삭제에 실패하면 [스타일 블록 삭제 실패] 토스트 메시지를 클라이언트 측에서 보여준다.

<hr>
관련 추가 작업

- [x] 클래스명 유효성 검증
- 시작: 영문자(A-Z, a-z), 밑줄(_), 또는 하이픈(-)
  토스트 안내 문구: `클래스명 첫 글자는 영문자, 밑줄(_), 하이픈(-)만 가능해요`
  
- 그외: 영문자(A-Z, a-z), 숫자(0-9), 밑줄(_), 또는 하이픈(-)
  토스트 안내 문구: `클래스명은 영문자, 밑줄(_), 하이픈(-), 숫자만 포함해주세요`

에러

- [x] 툴팁 우클릭하면 미세하게 크기때문에 스크롤이 생김
- [x] 툴팁 우클릭시 다른곳 클릭해도 툴팁 안닫힘.
        블록을 생성하거나, 툴팁의 "블록 삭제"를 눌러야지만 사라짐
- [x]  커스텀 flyout 쪽 생성하는 블록의 x축 쪽이 조금 떨어져야함
