### ISSUE TITLE
[1-2] 사용자는 추가된 워크스페이스 오른쪽 상단에 있는 [삭제] 버튼을 통해 삭제할 수 있다.

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#5]
## TASK
- [ ] 삭제버튼 클릭시 재확인 모달창 생성
- [ ] 모달창의 취소버튼 클릭시 모달창을 없앤다.
- [ ] 모달창의 삭제버튼 클릭시 해당 워크스페이스의 룸넘버로 서버에 삭제 요청을 하고 모달창을 없앤 후 로딩 화면을 보여준다.
- [ ] 삭제에 성공하면 로컬스토리지에서 해당 룸넘버 정보를 삭제하고 그리드뷰에서 워크스페이스 박스를 삭제한 후 [워크스페이스 삭제 완료] 토스트 메시지를 클라이언트 측에서 보여준다.
- [ ] 삭제에 실패하면 [워크스페이스 삭제 실패] 토스트 메시지를 클라이언트 측에서 보여준다.
