### ISSUE TITLE
아이콘 설정

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#60]
## TASK
아이콘 사용하기 위한 환경설정

## 📝 Todo
- [x] FIgma에서 사용하는 아이콘 정리
- [x] 아이콘 저장 (assets -> client/public/icons에 저장)
- [x] vite-plugin-svgr 설치
- [x] svg파일 import 테스트
