### ISSUE TITLE
Routing 설정

### ISSUE THREAD

**Issue by lee0jae330** [boostcampwm-2024/web31-BooLock#68]
## [기초작업]
- [ ] 각 페이지별 path를 설정한다.
- [ ] 잘못된 url로 접근했을 때 사용자에게 표시될 NotFound 페이지를 구현한다.

## 📝 Todo
- [ ] NotFound 페이지 디자인
- [ ] NotFound 구현
- [ ] Router 설정 추가
