### ISSUE TITLE
[0-5] 워크스페이스 삭제시 모달

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#69]
## TASK
홈에서 워크스페이스 hover시 나타나는 쓰레기통 아이콘 클릭시 삭제가 가능하다.
삭제는 DB에 영향을 주는 주요한 작업이므로 사용자에게 한 번 더 물어본다.

## 📝 Todo
- [x] 요소 FSD로 분리
- [x] UI 구현
- [x] React Portal로 띄우기
- [x] 배경 블러
- [x] 모달 열고 닫기 with zustand
