### ISSUE TITLE
[기초 작업] 공통 개발 환경 추가 세팅 (Git)

### ISSUE THREAD

**Issue by chichoc** [boostcampwm-2024/web31-BooLock#80]
## TASK
- 리뷰어 랜덤 2명 지정

### branch rule
- ~~브렌치 네이밍 강제~~
    husky 혹은 Github Action으로 제어해야 함
- [x] 브랜치 삭제 금지 (main, dev)
- [x] main으로 바로 merge 금지

### PR (dev브랜치)
- [x] reviewer 랜덤 2명 지정
- [x] 2명 모두 approve 하기 전에 merge 금지

### Github Actions
- [x] 브랜치네이밍
-  ~~main으로 바로 merge 금지 (hotfix, chore 브랜치는 가능)~~
