### ISSUE TITLE
[2-4] 사용자는 학습 컨텐츠 박스를 클릭하면 해당 학습 컨텐츠 워크스페이스로 이동한다.

### ISSUE THREAD

**Issue by inhachoi** [boostcampwm-2024/web31-BooLock#9]
## TASK

- [ ] 이미 학습이 완료되었거나, 학습중인 유저일 경우 클릭한 학습컨텐츠 페이지URL로 이동하며, DB 정보가 완전히 넘어오기 전까진 이동 중 로딩화면을 보여준다.
- [ ] 처음 학습하는 유저일 경우 이동 중 로딩화면을 보여준다.
- [ ] 서버에서 응답이 오기 전까지 전체 화면의 클릭을 비활성화 한다.
- [ ] 서버는 새로운 학습 컨텐츠 룸넘버 ID를 생성 후 학습 컨텐츠 템플릿을 해당 ID DB에 복붙하여 생성한다.
- [ ] 새로운 데이터 생성에 실패하면 클라이언트는 [컨텐츠 생성 실패] 토스크 메시지를 보여준다.
- [ ] 새로운 데이터 생성에 성공하면 해당 학습컨텐츠 페이지URL로 이동한다.
